import type {
  IToirAdapter,
  ToirEquipmentDto,
  ToirInspectionResultDto,
  ToirRouteDto,
} from './toir-adapter.interface.js';
import { WORKSHOP_NAME } from '@mobilny-obhodchik/shared';

/**
 * Synthetic 1C:TOIR adapter — realistic industrial data for hackathon demo.
 * Phase 2 target: replace with HttpToirAdapter talking to real 1C:TOIR REST.
 */
export class SyntheticToirAdapter implements IToirAdapter {
  private readonly equipment: ToirEquipmentDto[] = [
    {
      externalId: 'TOIR-KE-10',
      name: 'Котёл паровой КЕ-10',
      code: 'KE-10',
      type: 'BOILER',
      zone: WORKSHOP_NAME,
      locationDescription: 'Котельный зал, отметка +0.00, позиция 1',
      coordinates: { x: 120, y: 180 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 1,
      checklistTemplate: {
        version: 1,
        photoRequired: true,
        safetyNotes: [
          'Не приближаться к паропроводу без СИЗ',
          'Проверить наличие средств индивидуальной защиты',
        ],
        maintenanceHints: [
          'Уровень воды не ниже 50%',
          'Давление в рабочем диапазоне 10–14 бар',
        ],
        parameters: [
          {
            key: 'temperature',
            label: 'Температура пара',
            unit: '°C',
            type: 'number',
            min: 0,
            max: 240,
            warningMin: 150,
            warningMax: 210,
            criticalMin: 0,
            criticalMax: 220,
            required: true,
          },
          {
            key: 'pressure',
            label: 'Давление',
            unit: 'бар',
            type: 'number',
            min: 0,
            max: 16,
            warningMin: 8,
            warningMax: 14,
            criticalMin: 0,
            criticalMax: 15.5,
            required: true,
          },
          {
            key: 'waterLevel',
            label: 'Уровень воды',
            unit: '%',
            type: 'number',
            min: 0,
            max: 100,
            warningMin: 30,
            warningMax: 90,
            criticalMin: 20,
            criticalMax: 95,
            required: true,
          },
          {
            key: 'flameOk',
            label: 'Горелка исправна',
            unit: '',
            type: 'boolean',
            required: true,
          },
        ],
      },
      technicalSpecs: {
        manufacturer: 'Бийский котельный завод',
        model: 'КЕ-10-14',
        steamCapacity: '10 т/ч',
        workingPressure: '14 бар',
        year: 2019,
      },
      maintenanceDocs: [
        { title: 'Паспорт КЕ-10 (PDF)', url: '/docs/ke-10-passport.pdf' },
        { title: 'Регламент ТО', url: '/docs/ke-10-maintenance.pdf' },
      ],
    },
    {
      externalId: 'TOIR-PEN-1',
      name: 'Насос питательной воды ПЭН-1',
      code: 'PEN-1',
      type: 'PUMP',
      zone: WORKSHOP_NAME,
      locationDescription: 'Насосная, позиция 1',
      coordinates: { x: 260, y: 180 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 2,
      checklistTemplate: {
        version: 1,
        photoRequired: false,
        safetyNotes: ['СИЗ обязательны при работающем насосе'],
        maintenanceHints: ['Вибрация норма < 4.5 мм/с'],
        parameters: [
          {
            key: 'vibration',
            label: 'Вибрация',
            unit: 'мм/с',
            type: 'number',
            min: 0,
            max: 10,
            warningMax: 4.5,
            criticalMax: 7.1,
            required: true,
          },
          {
            key: 'bearingTemperature',
            label: 'Температура подшипника',
            unit: '°C',
            type: 'number',
            min: 0,
            max: 120,
            warningMax: 70,
            criticalMax: 90,
            required: true,
          },
          {
            key: 'current',
            label: 'Ток',
            unit: 'А',
            type: 'number',
            min: 0,
            max: 60,
            warningMax: 45,
            criticalMax: 55,
            required: true,
          },
        ],
      },
      technicalSpecs: { manufacturer: 'ГМС Ливгидромаш', model: 'ПЭ 65-40', flowRate: '65 м³/ч' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-PEN-2',
      name: 'Насос питательной воды ПЭН-2',
      code: 'PEN-2',
      type: 'PUMP',
      zone: WORKSHOP_NAME,
      locationDescription: 'Насосная, позиция 2',
      coordinates: { x: 260, y: 260 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 3,
      checklistTemplate: {
        version: 1,
        photoRequired: false,
        safetyNotes: ['СИЗ обязательны при работающем насосе'],
        maintenanceHints: ['Вибрация норма < 4.5 мм/с'],
        parameters: [
          {
            key: 'vibration',
            label: 'Вибрация',
            unit: 'мм/с',
            type: 'number',
            warningMax: 4.5,
            criticalMax: 7.1,
            required: true,
          },
          {
            key: 'bearingTemperature',
            label: 'Температура подшипника',
            unit: '°C',
            type: 'number',
            warningMax: 70,
            criticalMax: 90,
            required: true,
          },
          {
            key: 'current',
            label: 'Ток',
            unit: 'А',
            type: 'number',
            warningMax: 45,
            criticalMax: 55,
            required: true,
          },
        ],
      },
      technicalSpecs: { manufacturer: 'ГМС Ливгидромаш', model: 'ПЭ 65-40', flowRate: '65 м³/ч' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-DA-15',
      name: 'Деаэратор ДА-15',
      code: 'DA-15',
      type: 'DEAERATOR',
      zone: WORKSHOP_NAME,
      locationDescription: 'Деаэраторная, отметка +6.00',
      coordinates: { x: 400, y: 180 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 4,
      checklistTemplate: {
        version: 1,
        photoRequired: true,
        safetyNotes: ['Температура деаэрации ~104 °C — опасность ожога'],
        maintenanceHints: ['Давление рабочее 1.2 бар'],
        parameters: [
          {
            key: 'pressure',
            label: 'Давление',
            unit: 'бар',
            type: 'number',
            warningMin: 1.0,
            warningMax: 1.3,
            criticalMin: 0.8,
            criticalMax: 1.5,
            required: true,
          },
          {
            key: 'temperature',
            label: 'Температура',
            unit: '°C',
            type: 'number',
            warningMin: 100,
            warningMax: 107,
            criticalMax: 115,
            required: true,
          },
          {
            key: 'level',
            label: 'Уровень воды',
            unit: '%',
            type: 'number',
            warningMin: 40,
            warningMax: 80,
            criticalMin: 25,
            criticalMax: 90,
            required: true,
          },
        ],
      },
      technicalSpecs: { model: 'ДА-15', volume: '15 м³' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-VK-25',
      name: 'Компрессор ВК-25',
      code: 'VK-25',
      type: 'COMPRESSOR',
      zone: WORKSHOP_NAME,
      locationDescription: 'Компрессорная',
      coordinates: { x: 540, y: 180 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 5,
      checklistTemplate: {
        version: 1,
        photoRequired: false,
        safetyNotes: [],
        maintenanceHints: ['Проверить масляный фильтр'],
        parameters: [
          {
            key: 'pressure',
            label: 'Давление нагнетания',
            unit: 'бар',
            type: 'number',
            warningMax: 8.5,
            criticalMax: 10,
            required: true,
          },
          {
            key: 'temperature',
            label: 'Температура',
            unit: '°C',
            type: 'number',
            warningMax: 90,
            criticalMax: 105,
            required: true,
          },
          {
            key: 'current',
            label: 'Ток',
            unit: 'А',
            type: 'number',
            warningMax: 80,
            criticalMax: 95,
            required: true,
          },
          {
            key: 'vibration',
            label: 'Вибрация',
            unit: 'мм/с',
            type: 'number',
            warningMax: 4.5,
            criticalMax: 7.1,
            required: true,
          },
        ],
      },
      technicalSpecs: { model: 'ВК-25', capacity: '25 м³/мин' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-DM-1',
      name: 'Электродвигатель ДМ-1',
      code: 'DM-1',
      type: 'MOTOR',
      zone: WORKSHOP_NAME,
      locationDescription: 'Моторный зал',
      coordinates: { x: 540, y: 300 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 6,
      checklistTemplate: {
        version: 1,
        photoRequired: false,
        safetyNotes: ['Не касаться корпуса без проверки заземления'],
        maintenanceHints: [],
        parameters: [
          {
            key: 'temperature',
            label: 'Температура корпуса',
            unit: '°C',
            type: 'number',
            warningMax: 75,
            criticalMax: 90,
            required: true,
          },
          {
            key: 'current',
            label: 'Ток',
            unit: 'А',
            type: 'number',
            warningMax: 110,
            criticalMax: 130,
            required: true,
          },
          {
            key: 'vibration',
            label: 'Вибрация',
            unit: 'мм/с',
            type: 'number',
            warningMax: 4.5,
            criticalMax: 7.1,
            required: true,
          },
        ],
      },
      technicalSpecs: { model: 'АИР200L2', power: '45 кВт' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-TM-400',
      name: 'Трансформатор ТМ-400',
      code: 'TM-400',
      type: 'TRANSFORMER',
      zone: WORKSHOP_NAME,
      locationDescription: 'Распределительная подстанция',
      coordinates: { x: 400, y: 380 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 7,
      checklistTemplate: {
        version: 1,
        photoRequired: true,
        safetyNotes: ['Высокое напряжение! Только с допуском', 'Работа в присутствии ответственного'],
        maintenanceHints: ['Проверить уровень масла', 'Проверить силикагель'],
        parameters: [
          {
            key: 'oilTemperature',
            label: 'Температура масла',
            unit: '°C',
            type: 'number',
            warningMax: 75,
            criticalMax: 90,
            required: true,
          },
          {
            key: 'loadPercent',
            label: 'Загрузка',
            unit: '%',
            type: 'number',
            warningMax: 85,
            criticalMax: 100,
            required: true,
          },
        ],
      },
      technicalSpecs: { model: 'ТМ-400/10', power: '400 кВА' },
      maintenanceDocs: [],
    },
    {
      externalId: 'TOIR-RU-10',
      name: 'Распределительный щит РУ-10 кВ',
      code: 'RU-10',
      type: 'SWITCHGEAR',
      zone: WORKSHOP_NAME,
      locationDescription: 'Распределительная подстанция, щитовая',
      coordinates: { x: 260, y: 380 },
      routeExternalId: 'TOIR-ROUTE-PRIMARY',
      sequenceOrder: 8,
      checklistTemplate: {
        version: 1,
        photoRequired: true,
        safetyNotes: ['Высокое напряжение!', 'Работать только в диэлектрических перчатках'],
        maintenanceHints: [],
        parameters: [
          {
            key: 'voltageA',
            label: 'Напряжение фаза A',
            unit: 'кВ',
            type: 'number',
            warningMin: 9.5,
            warningMax: 10.5,
            criticalMin: 9.0,
            criticalMax: 11.0,
            required: true,
          },
          {
            key: 'voltageB',
            label: 'Напряжение фаза B',
            unit: 'кВ',
            type: 'number',
            warningMin: 9.5,
            warningMax: 10.5,
            criticalMin: 9.0,
            criticalMax: 11.0,
            required: true,
          },
          {
            key: 'voltageC',
            label: 'Напряжение фаза C',
            unit: 'кВ',
            type: 'number',
            warningMin: 9.5,
            warningMax: 10.5,
            criticalMin: 9.0,
            criticalMax: 11.0,
            required: true,
          },
          {
            key: 'current',
            label: 'Ток нагрузки',
            unit: 'А',
            type: 'number',
            warningMax: 300,
            criticalMax: 380,
            required: true,
          },
          {
            key: 'temperature',
            label: 'Температура шин',
            unit: '°C',
            type: 'number',
            warningMax: 65,
            criticalMax: 85,
            required: true,
          },
        ],
      },
      technicalSpecs: { model: 'КСО-285', voltage: '10 кВ' },
      maintenanceDocs: [],
    },
  ];

  private readonly routes: ToirRouteDto[] = [
    {
      externalId: 'TOIR-ROUTE-PRIMARY',
      name: 'Основной маршрут — Энергоцех',
      description: '12 контрольных точек по котельному залу, насосной, ТП и распредщиту',
      zone: WORKSHOP_NAME,
      estimatedDurationMinutes: 75,
      mapGeoJSON: {
        type: 'FeatureCollection',
        viewBox: [0, 0, 720, 480],
        walls: [
          { id: 'w-outer', points: [[20, 20], [700, 20], [700, 460], [20, 460], [20, 20]] },
          { id: 'w-zone1', points: [[20, 240], [700, 240]] },
          { id: 'w-zone2', points: [[360, 20], [360, 460]] },
        ],
        zones: [
          { id: 'z1', name: 'Котельный зал', rect: [20, 20, 340, 220], color: '#eef5ff' },
          { id: 'z2', name: 'Насосная', rect: [360, 20, 340, 220], color: '#fff8e6' },
          { id: 'z3', name: 'Моторный зал', rect: [20, 240, 340, 220], color: '#fff0f0' },
          { id: 'z4', name: 'Распределительная', rect: [360, 240, 340, 220], color: '#f0fff4' },
        ],
      },
    },
    {
      externalId: 'TOIR-ROUTE-SECONDARY',
      name: 'Контур освещения и КИП',
      description: '6 дополнительных точек для вспомогательного оборудования',
      zone: WORKSHOP_NAME,
      estimatedDurationMinutes: 30,
      mapGeoJSON: {
        type: 'FeatureCollection',
        viewBox: [0, 0, 720, 480],
        walls: [{ id: 'w-outer', points: [[20, 20], [700, 20], [700, 460], [20, 460], [20, 20]] }],
        zones: [{ id: 'z1', name: 'Вспомогательные зоны', rect: [20, 20, 680, 440], color: '#f4f4f5' }],
      },
    },
  ];

  async getRoutes(): Promise<ToirRouteDto[]> {
    return this.routes;
  }

  async getEquipment(): Promise<ToirEquipmentDto[]> {
    return this.equipment;
  }

  async syncInspectionResult(
    result: ToirInspectionResultDto,
  ): Promise<{ accepted: boolean; externalId?: string }> {
    // Phase 1: no-op. Phase 2 will POST to 1C:TOIR REST endpoint.
    return { accepted: true, externalId: `TOIR-SYNC-${result.inspectionId}` };
  }
}
